// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"kube-management-platform/internal/biz"
	"kube-management-platform/internal/conf"
	"kube-management-platform/internal/data"
	"kube-management-platform/internal/server"
	"kube-management-platform/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, confKube *conf.Kube, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, confKube, logger)
	if err != nil {
		return nil, nil, err
	}
	kubeDeploymentRepo := data.NewKubeDeploymentRepo(dataData, logger)
	kubeUsecase := biz.NewKubeUsecase(kubeDeploymentRepo, logger)
	kubeService := service.NewKubeService(kubeUsecase)
	grpcServer := server.NewGRPCServer(confServer, kubeService, logger)
	httpServer := server.NewHTTPServer(confServer, kubeService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
